import {
  ArrowRight,
  Bot,
  Building2,
  Clapperboard,
  Clock,
  Cloud,
  Code2,
  Eye,
  Gem,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  HeartPulse,
  Landmark,
  Laptop,
  LifeBuoy,
  Megaphone,
  PenTool,
  Plane,
  Rocket,
  Search,
  Share2,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Target,
  TrendingUp,
  Truck,
  Users,
  Zap,
  LayoutDashboard,
  type LucideIcon,
} from "lucide-react";

/** String → lucide icon map so content files can stay serialisable. */
const map: Record<string, LucideIcon> = {
  globe: Globe,
  code: Code2,
  smartphone: Smartphone,
  "pen-tool": PenTool,
  clapperboard: Clapperboard,
  share: Share2,
  search: Search,
  "trending-up": TrendingUp,
  sparkles: Sparkles,
  target: Target,
  cloud: Cloud,
  "life-buoy": LifeBuoy,
  landmark: Landmark,
  "heart-pulse": HeartPulse,
  "shopping-bag": ShoppingBag,
  "graduation-cap": GraduationCap,
  truck: Truck,
  "building-2": Building2,
  users: Users,
  clock: Clock,
  eye: Eye,
  gem: Gem,
  handshake: Handshake,
  zap: Zap,
  heart: Heart,
  rocket: Rocket,
  laptop: Laptop,
  plane: Plane,
  bot: Bot,
  megaphone: Megaphone,
  "layout-dashboard": LayoutDashboard,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = map[name] ?? ArrowRight;
  return <Cmp className={className} aria-hidden strokeWidth={1.75} />;
}
